### ISSUE TITLE
Biscuit stuck at top left of screen in mobile

### ISSUE THREAD

**Issue by mdunlap15** [88mpg/shuffleboard#1]
@88mpg @laaan

When I attempt to drag a biscuit in mobile, the biscuit jumps to the top left corner of the screen and then can't be moved.
![SmartSelect_20190519-164741_Chrome](https://user-images.githubusercontent.com/42551377/57987933-fd2e7580-7a55-11e9-8946-e81dcc0813b6.jpg)

**Comment by 88mpg** [comment]
Haven't run into this, what's your OS and browser?

**Comment by mdunlap15** [comment]
> Haven't run into this, what's your OS and browser?

Android 9; SM-G973U Build/PPR1.180610.011
Chrome 74.0.3729.157

**Comment by 88mpg** [comment]
Just tested on Browserstack, definitely a bug. If I get some free time today I'll try and debug.

Full disclosure Ian and I threw this together in an afternoon and didn't expect anyone but us to use it. Now that it's getting some use we've been tossing around ideas of making something more stable from scratch.

I'll look into this in the meantime since it's most likely an issue across all Android devices, thanks for flagging it.

**Comment by mdunlap15** [comment]
> Just tested on Browserstack, definitely a bug. If I get some free time today I'll try and debug.
> 
> Full disclosure Ian and I threw this together in an afternoon and didn't expect anyone but us to use it. Now that it's getting some use we've been tossing around ideas of making something more stable from scratch.
> 
> I'll look into this in the meantime since it's most likely an issue across all Android devices, thanks for flagging it.

No worries.  Good luck with the big match tonight.

**Comment by 88mpg** [comment]
This is deprecated, new version in the works.
